version: '2'

services:
  datastore:
    image: busybox
    volumes:
        - /var/lib/mysql
  iron:
    build: ./iron
    volumes:
      - .:/app
    ports:
      - "90:90"
    links:
      - db:db
    depends_on:
      - db
  server:
    image: nginx
    ports:
      - "80:80"
    links:
    - iron:iron
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public/html:/var/www/html
      - ./public/css:/var/www/css
      - ./public/js:/var/www/js
  db:
    build: ./db
    volumes_from:
      - datastore
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mydb
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
