version: '2'

services:
  iron:
    build: .
    volumes:
      - .:/app
    ports:
      - "90:90"
  server:
    image: nginx:1.13.5-alpine
    ports:
      - "80:80"
    links:
    - iron:iron
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public/html:/var/www/html
      - ./public/css:/var/www/css
      - ./public/js:/var/www/js
